import 'angular'
import 'angular-animate'
import 'angular-aria'
import 'angular-material'
import 'angular-material/angular-material.css'
import 'angular-resource'
import 'plupload'
import 'qiniu-js'

import './app.css'
import './app'
import './controllers'
import './components'
import './pages'
import './services'
